// Generated by CoffeeScript 1.6.3
var LoginWidget, SignupWidget, attach_login;

SignupWidget = (function() {
  var DEFAULT_NEXT, WIDGET_TMPL;

  DEFAULT_NEXT = '/';

  WIDGET_TMPL = '<div>\n  <div>\n    <span>Name</span>\n    <input placeholder="First" class="first-name-input" type="text"></input>\n    <input placeholder="Last" class="last-name-input" type="text"></input>\n  </div>\n  <div>\n    <span>Username</span>\n    <input class="username-input" type="text"></input>\n  <div>\n  <div>\n    <span>Password</span>\n    <input class="password-input" type="text"></input>\n  <div>\n  <button class="sign-up-button">Sign up!</button>\n  <div class="status-area"></div>\n</div>';

  function SignupWidget(defaults, next) {
    if (defaults == null) {
      defaults = {};
    }
    this.next = next != null ? next : DEFAULT_NEXT;
    this._elt = $(WIDGET_TMPL);
    (this._elt.find('button.sign-up-button')).click(this.do_signup.bind(this));
    if (defaults.username != null) {
      (this._elt.find('input.username-input')).val(defaults.username);
    }
    if (defaults.password != null) {
      (this._elt.find('input.password-input')).val(defaults.password);
    }
    this._status_area = this._elt.find('div.status-area');
  }

  SignupWidget.prototype.elt = function() {
    return this._elt;
  };

  SignupWidget.prototype.set_status = function(text) {
    return this._status_area.text(text);
  };

  SignupWidget.prototype.do_signup = function() {
    var data, first_name, last_name, password, username,
      _this = this;
    first_name = this._elt.find('input.first-name-input').val();
    last_name = this._elt.find('input.last-name-input').val();
    username = this._elt.find('input.username-input').val();
    password = this._elt.find('input.password-input').val();
    if (first_name === '' || last_name === '') {
      return this.set_status("Invalid first or last name.");
    }
    if (username === '' || password === '') {
      return this.set_status("Invalid username or password.");
    }
    data = {
      username: username,
      password: password,
      signup: true,
      info: {
        first_name: first_name,
        last_name: last_name
      }
    };
    return $ajax('/login', data, 'post', function(err, res) {
      if (err) {
        return _this.set_status(err);
      }
      if (!res.success) {
        return _this.set_status(res);
      }
      return window.location.href = _this.next;
    });
  };

  return SignupWidget;

})();

LoginWidget = (function() {
  var DEFAULT_NEXT, WIDGET_TMPL;

  DEFAULT_NEXT = '/';

  WIDGET_TMPL = '<div>\n  <span>Username</span><input class="username-input" type="text"></input>\n  <span>Password</span><input class="password-input" type="text"></input>\n  <button class="login-button">Login</button>\n  <button class="sign-up-button">Sign up</button>\n  <div class="status-area"></div>\n</div>';

  function LoginWidget(on_signup, next) {
    this.next = next != null ? next : DEFAULT_NEXT;
    this._elt = $(WIDGET_TMPL);
    this._username_input = this._elt.find('input.username-input');
    this._password_input = this._elt.find('input.password-input');
    this._status_area = this._elt.find('div.status-area');
    (this._elt.find('button.login-button')).click(this.do_login.bind(this));
    (this._elt.find('button.sign-up-button')).click(on_signup);
  }

  LoginWidget.prototype.elt = function() {
    return this._elt;
  };

  LoginWidget.prototype.get_values = function() {
    var ret;
    ret = {
      username: this._username_input.val(),
      password: this._password_input.val()
    };
    return ret;
  };

  LoginWidget.prototype.set_status = function(text) {
    return this._status_area.text(text);
  };

  LoginWidget.prototype.do_login = function() {
    var data,
      _this = this;
    data = this.get_values();
    return $ajax('/login', data, 'post', function(err, res) {
      if (err) {
        return _this.set_status(err);
      }
      if (!res.success) {
        return _this.set_status(res);
      }
      return window.location.href = _this.next;
    });
  };

  return LoginWidget;

})();

attach_login = function(container) {
  var login_widget;
  login_widget = new LoginWidget(function() {
    var defaults, password, signup_widget, username, _ref;
    _ref = login_widget.get_values(), username = _ref.username, password = _ref.password;
    container.empty();
    defaults = {
      username: username,
      password: password
    };
    signup_widget = new SignupWidget(defaults);
    return container.append(signup_widget.elt());
  });
  return container.append(login_widget.elt());
};
