// Generated by IcedCoffeeScript 1.6.2d
(function() {
  var clone, shuffle;



  clone = function(item) {
    return JSON.parse(JSON.stringify(item));
  };

  shuffle = function(array) {
    var i, j, temp, _results;
    i = array.length - 1;
    _results = [];
    while (i > 0) {
      j = Math.floor(Math.random() * (i + 1));
      temp = array[i];
      array[i] = array[j];
      array[j] = temp;
      _results.push(i--);
    }
    return _results;
  };

  exports.clone = clone;

  exports.shuffle = shuffle;

}).call(this);
