#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR=$SCRIPT_DIR/..

# TODO: install nodejs
# TODO: install mysql
# TODO: configure mysql?

# Install node packages:
# Alternatively, do `sudo npm install -g browserify`
npm install browserify
npm install coffee-script
npm install express
npm install iced-coffee-script
npm install mustache
npm install mysql
npm install socket.io
npm install through

./dev.sh
scripts/tichu_start

# Now visit http://localhost:8888 or http://localhost:8888/quadcopter.html